CREATE TABLE produtos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(255) NOT NULL,
    descricao VARCHAR2(500),
    preco NUMBER(10, 2) NOT NULL,
    quantidade NUMBER(10) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

-- Índice para melhorar a pesquisa por nome de produto
CREATE INDEX idx_produtos_nome ON produtos(nome);